version: "3.8"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8990:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: yourpassword
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3030:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge